# Generated by Django 2.0.1 on 2018-01-24 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spauser',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
